slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: "odom"
    base_frame: "base_footprint"
    map_frame: "map"
    scan_topic: "scan"
    
    odom_model_type: "Holonomic"
    use_odom: true
    publish_tf: true

    # optional tuning
    map_update_interval: 0.5
    max_laser_range: 10.0
