controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # List of controllers to load
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    # No additional parameters needed for basic operation

# Mecanum Drive Controller Configuration
mecanum_drive_controller:
  ros__parameters:
    # Wheel joint names - MUST match your URDF
    front_left_wheel_joint: wheel_fl_joint
    front_right_wheel_joint: wheel_fr_joint
    rear_left_wheel_joint: wheel_rl_joint
    rear_right_wheel_joint: wheel_rr_joint
    
    # Robot physical dimensions (in meters)
    # Distance from front wheels to rear wheels
    wheel_separation_x: 0.342  # 2 * 0.171 meters
    
    # Distance from left wheels to right wheels  
    wheel_separation_y: 0.72496  # 2 * 0.36248 meters
    
    # Wheel radius (in meters)
    wheel_radius: 0.05  # 50mm = 0.05 meters
    
    # Kinematics parameters
    kinematics:
      type: mecanum
    
    # Odometry settings
    odom_frame_id: odom
    base_frame_id: base_link
    
    # Enable odometry
    enable_odom_tf: true
    
    # Odometry covariances
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Publishing settings
    publish_rate: 50.0  # Hz
    
    # Command velocity settings
    cmd_vel_timeout: 0.5  # seconds - stop if no cmd_vel received
    use_stamped_vel: false  # Use geometry_msgs/Twist instead of TwistStamped
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8  # m/s^2
      y:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8  # m/s^2
    
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.5  # rad/s^2