mecanum_drive_controller:
  ros__parameters:
    # Joint names ของล้อ (ต้องตรงกับ URDF)
    front_left_wheel:  'wheel_fl_joint'
    front_right_wheel: 'wheel_fr_joint'
    rear_left_wheel:   'wheel_rl_joint'
    rear_right_wheel:  'wheel_rr_joint'

    # ขนาดหุ่น
    wheel_separation_x: 0.30   # ระยะห่างซ้าย-ขวา (m)
    wheel_separation_y: 0.30   # ระยะห่างหน้า-หลัง (m)
    wheel_radius: 0.05         # รัศมีล้อ (m)

    # Frame IDs
    odom_frame_id: odom
    base_frame_id: base_link

    # พารามิเตอร์อื่น ๆ
    publish_rate: 50.0
    cmd_vel_timeout: 0.25
    enable_odom_tf: true